using System;

namespace RESTable.Meta;

/// <summary>
///     The kinds of resources in RESTable
/// </summary>
[Flags]
public enum ResourceKind
{
    /// <summary />
    None = 0,

    /// <summary>
    ///     Holds a set of entities that can be manipulated using REST methods like GET and POST
    /// </summary>
    EntityResource = 1 << 0,

    /// <summary>
    ///     Small interactive applications that can be run over a WebSocket
    /// </summary>
    TerminalResource = 1 << 1,

    /// <summary>
    ///     Holds raw binary data
    /// </summary>
    BinaryResource = 1 << 2,

    /// <summary>
    ///     Entities of event resources are generated by the RESTable application when certain
    ///     events are raised. They can be listened for by, for example, webhooks.
    /// </summary>
    EventResource = 1 << 3,

    /// <summary>
    ///     Matches all resource kinds
    /// </summary>
    All = ~None
}